CREATE DATABASE QL_BANHANG
GO
USE QL_BANHANG
GO

CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10) NOT NULL,
	HOTENKH NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH NVARCHAR(10) NOT NULL,
	DIACHI NVARCHAR(80) NOT NULL,
	SDT VARCHAR(11) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)
)
CREATE TABLE NHASANXUAT
(
	MANSX VARCHAR(10) NOT NULL,
	TENNSX NVARCHAR(50) NOT NULL,
	SDT VARCHAR(11) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(80) NOT NULL,
	CONSTRAINT PK_NHASANXUAT PRIMARY KEY(MANSX)
)

CREATE TABLE LOAIHANG
(
	MALOAI VARCHAR(10) NOT NULL,
	TENLOAI NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_LOAIHANG PRIMARY KEY(MALOAI)
)

CREATE TABLE HANGHOA
(
	MAHG VARCHAR(10) NOT NULL,
	TENHG NVARCHAR(50) NOT NULL,
	DVT NVARCHAR(20) NOT NULL,
	SOLUONGTON INT CHECK(SOLUONGTON >= 0) NOT NULL,
	MALOAI VARCHAR(10) NOT NULL,
	MANSX VARCHAR(10) NOT NULL,
	MOTA NVARCHAR(MAX) NULL,
    HINHANH VARCHAR(255) NULL,
	GIABAN DECIMAL(18, 2) NOT NULL,
	CONSTRAINT PK_HANGHOA PRIMARY KEY(MAHG),
	CONSTRAINT FK_HANGHOA_LOAIHANG FOREIGN KEY(MALOAI) REFERENCES LOAIHANG(MALOAI),
	CONSTRAINT FK_HANGHOA_NHASANXUAT FOREIGN KEY(MANSX) REFERENCES NHASANXUAT(MANSX)
)

CREATE TABLE HOADON
(
	MAHD VARCHAR(10) NOT NULL,
	NGAYLAP DATE NOT NULL DEFAULT GETDATE(),
	TRANGTHAI NVARCHAR(50) NOT NULL,
	MAKH VARCHAR(10) NOT NULL,
	CONSTRAINT PK_HOADON PRIMARY KEY(MAHD),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CHITIETHD
(
	MAHD VARCHAR(10) NOT NULL,
	MAHG VARCHAR(10) NOT NULL,
	SOLUONG INT NOT NULL,
	GIABAN DECIMAL(18,2) NOT NULL,
	CONSTRAINT PK_CHITIETHD PRIMARY KEY(MAHD, MAHG),
	CONSTRAINT FK_CHITIETHD_HOADON FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CHITIETHD_HANGHOA FOREIGN KEY(MAHG) REFERENCES HANGHOA(MAHG),
	CONSTRAINT CHK_CHITIETHD CHECK(SOLUONG >= 0 AND GIABAN >= 0)
)

CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(10) NOT NULL,
	TENNCC NVARCHAR(50) NOT NULL,
	SDT VARCHAR(11) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(80) NOT NULL,
	CONSTRAINT PK_NHACUNGCAP PRIMARY KEY(MANCC)
)

CREATE TABLE PHIEUNHAP
(
	MAPN VARCHAR(10) NOT NULL,
	NGAYNHAP DATE NOT NULL DEFAULT GETDATE(),
	MANCC VARCHAR(10) NOT NULL,
	CONSTRAINT PK_PHIEUNHAP PRIMARY KEY(MAPN),
	CONSTRAINT FK_PHIEUNHAP_NHACUNGCAP FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP(MANCC)
)

CREATE TABLE CHITIETPN
(
	MAPN VARCHAR(10) NOT NULL,
	MAHG VARCHAR(10) NOT NULL,
	SOLUONG INT NOT NULL,
	GIANHAP DECIMAL(18,2) NOT NULL,
	CONSTRAINT PK_CHITIETPN PRIMARY KEY(MAPN, MAHG),
	CONSTRAINT FK_CHITIETPN_PHIEUNHAP FOREIGN KEY(MAPN) REFERENCES PHIEUNHAP(MAPN),
	CONSTRAINT FK_CHITIETPN_HANGHOA FOREIGN KEY(MAHG) REFERENCES HANGHOA(MAHG),
	CONSTRAINT CHK_CHITIETPN CHECK(SOLUONG >= 0 AND GIANHAP >= 0)
)

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH NVARCHAR(10) NOT NULL,
	DIACHI NVARCHAR(80) NOT NULL,
	SDT VARCHAR(11) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	CHUCVU NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
)

CREATE TABLE TAIKHOAN
(
	MATK INT IDENTITY(1,1) NOT NULL,
	TENDN NVARCHAR(50) UNIQUE NOT NULL,
	MATKHAU VARCHAR(100) NOT NULL,
	VAITRO NVARCHAR(30) NOT NULL,
	MANV VARCHAR(10) NULL,
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY(MATK),
	CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
)

INSERT INTO KHACHHANG VALUES
('KH001', N'Nguyễn Văn An', '1998-05-12', N'Nam', N'12 Lê Lợi, TP.HCM', '0901234567', 'vana@gmail.com'),
('KH002', N'Lê Thị Bích', '2000-08-23', N'Nữ', N'45 Hai Bà Trưng, Hà Nội', '0912345678', 'lethib@gmail.com'),
('KH003', N'Trần Văn Cường', '1995-10-05', N'Nam', N'78 Nguyễn Huệ, TP.HCM', '0933333333', 'tvanc@gmail.com'),
('KH004', N'Phạm Thị Diễm', '1999-03-15', N'Nữ', N'89 CMT8, Cần Thơ', '0944444444', 'phamd@gmail.com'),
('KH005', N'Lê Văn Long', '1997-07-07', N'Nam', N'11 Pasteur, TP.HCM', '0955555555', 'levane@gmail.com'),
('KH006', N'Đỗ Thị Lợi', '2001-12-30', N'Nữ', N'25 Hùng Vương, Đà Nẵng', '0966666666', 'dothif@gmail.com'),
('KH007', N'Phan Văn Giàu', '1994-09-20', N'Nam', N'09 Trần Hưng Đạo, Huế', '0977777777', 'phanvg@gmail.com'),
('KH008', N'Hoàng Thị Yến', '1996-11-11', N'Nữ', N'19 Quang Trung, Hà Nội', '0988888888', 'hoangth@gmail.com'),
('KH009', N'Ngô Văn Kiều', '1993-06-17', N'Nam', N'22 Điện Biên Phủ, TP.HCM', '0999999999', 'ngovi@gmail.com'),
('KH010', N'Đinh Thị Định', '2002-02-02', N'Nữ', N'33 Nguyễn Văn Cừ, Đà Nẵng', '0900000000', 'dinhthij@gmail.com');
SELECT*FROM KHACHHANG

INSERT INTO NHASANXUAT VALUES
('NSX001', N'CocaCola', '0123456789', 'contact@cocacola.com', N'Mỹ'),
('NSX002', N'Haribo', '0987654321', 'support@amd.com', N'Mỹ'),
('NSX003', N'Acecook', '0909090909', 'info@acecook.com', N'Nhật'),
('NSX004', N'Vifon', '0911111111', 'contact@vifon.com', N'Việt Nam'),
('NSX005', N'Chupa Chups', '0922222222', 'support@chupachups.com', N'Tây Ban Nha'),
('NSX006', N'Orion', '0933333333', 'info@orion.com', N'Hàn Quốc'),
('NSX007', N'Tường An', '0944444444', 'sales@tuongan.com', N'Việt Nam'),
('NSX008', N'Chinsu', '0955555555', 'chinsu-usa@msc.masangroup.com', N'Mỹ'),
('NSX009', N'Samyang', '0966666666', 'contact@samyang.com', N'Hàn Quốc'),
('NSX010', N'Trung Nguyên Legend', '0977777777', 'cs@trungnguyenlegend.com', N'Việt Nam');
SELECT*FROM NHASANXUAT


INSERT INTO LOAIHANG VALUES
('LH001', N'Mì gói'),
('LH002', N'Mì cay'),
('LH003', N'Kẹo'),
('LH004', N'Bánh'),
('LH005', N'Dầu ăn'),
('LH006', N'Nước tương'),
('LH007', N'Nước mắm'),
('LH008', N'Cà phê'),
('LH009', N'Phở gói'),
('LH010', N'Tương ớt'),
('LH011', N'Nước ngọt');
SELECT*FROM LOAIHANG

